### ISSUE TITLE
Names are replaced by durability (Paper)

### ISSUE THREAD

**Issue by FlorianKoerner** [Explorers-Eden/Automaticons#1]
Hello, first of all: Great Datapack. Really a lot of fun. Thanks for all the work! 🥳

Unfortunately I have a small problem. Some automaticons suddenly have the durability at the top instead of the name and the durability at the bottom is no longer updated.

That's not a big problem in itself, but it also doesn't update when you provide a new tool. As a result, it quickly becomes confusing who still needs a new tool.

Current workaround: Give a new tool, then remove it and place it again.

![image](https://github.com/user-attachments/assets/71ec58b2-b9ea-45b2-a9b3-b946c8e2382e)

**Comment by NiceKaleido** [comment]
Check whether u have enabled scorebord entries for non player entities and also if that problem occurs without other plugin/datapacks.

It's fully tested on papermc 1.21 and should work. It rather sounds like another plugin/datapack is messing something up

**Comment by FlorianKoerner** [comment]
Hi @NiceKaleido 

I have just started a new Paper 1.21 Server with only Automaticons. I was also able to reproduce the error in this environment.

The server settings are all set to default. This includes the paper setting for the scoreboards.

```
scoreboards:
  allow-non-player-entities-on-scoreboards: true
```

I can reproduce the error as follows:

1. placing multiple automaticons (stone pickaxe).
2. place raw copper in the hands of the automaticons.
3. wait until the first drop.

![image](https://github.com/user-attachments/assets/6eaf26b8-901c-4917-b90e-0010fde81d33)

**Comment by NiceKaleido** [comment]
Thanks - I could replicate this on the latest paper release. Seems like Paper is not handling the nearest entity correctly. I've fixed this issue in the latest release.


https://modrinth.com/datapack/automaticons/version/1.7b

**Comment by FlorianKoerner** [comment]
Looks good. Thank you. :)
