### ISSUE TITLE
Not working. 1.21.1

### ISSUE THREAD

**Issue by thijsi123** [Explorers-Eden/Automaticons#2]
Mod version automaticons-1.7c.jar
Game version 1.21.1
Fabric version 0.16.5

downloaded using modrinth manager/app from: https://modrinth.com/datapack/automaticons

I'm having an issue.
Followed this recipe shown in: https://explorerseden.eu/wiki/automaticons/overview

It doesn't work, in jei, nothing shows up.

What I did.
Put a list of mods together, start the game, create the world, play, close the game, install this mod, launch the world, and nothing happens - I'm here.

![image](https://github.com/user-attachments/assets/ed6efd1c-ad11-47e4-8438-693f70c34930)
Mod shows up.

**Comment by NiceKaleido** [comment]
Not an issue with Automaticons since it's mod version is only an auto compiled data pack.

**Comment by Soforak** [comment]
Same problem for me on Neoforge, not working on server and in solo, I can craft them following the exemple but can't find the craft and I don't know how to use them

**Comment by AntoninJuquel** [comment]
How is this closed ? I tried both using the mod and 'just' dropping the datapack in the datapacks folder and it still doesnt work
@NiceKaleido

**Comment by NiceKaleido** [comment]
it's closed since it will not work with JEI. There's nothing I can do on my end for it to work.
