### ISSUE TITLE
Missing translation key is messing with server console

### ISSUE THREAD

**Issue by suerion** [Explorers-Eden/Automaticons#3]
Hey, i had used your Mod and come here fore the issue i had found.

In your mod there are missing some translation keys, after adding your mod, it messing with the server console.

should be like this
Preparing spawn area: 2%

but is this
[23:12:13] [Worker-Main-4/INFO]: menu.preparingSpawn

Hope you could fix it :)

Fabric 1.21.1

**Comment by NiceKaleido** [comment]
And which translation keys are missing? The error isn't indicating anything related to that.

**Comment by suerion** [comment]
With your mod, the server console is messed up like this i had show , without it, the console works fine.

This is only a cosmetic error

**Comment by NiceKaleido** [comment]
I can't replicate the issue. "menu.preparingSpawn" is also not a translation key used by this data pack / converted mod.

**Comment by NiceKaleido** [comment]
It might just be that u'r missing a translation key from another mod which causes the "menu.preparingSpawn" as translation key and not "Preparing spawn area:"

**Comment by suerion** [comment]
Other mod devs could fix it.

Without automaticon it work fine, console works fine, after adding automaticon, the console log is messed up 🤷‍♂️ had disabled a lot mods and enabled again, it is only  with automaticon...

I had a list, what mods are messing around with language tags. The most More .... Mods are also messing around, with the tags, but they could not fix it, because they had an feature whats dissabled if they would change it... etc...

**Comment by NiceKaleido** [comment]
I am sorry for you having trouble, but as said neither is this a translation key provided by the data pack nor can I reproduce this issue.

**Comment by suerion** [comment]
> I am sorry for you having trouble, but as said neither is this a translation key provided by the data pack nor can I reproduce this issue.

@NiceKaleido had found a new information for the tags with missing language,

if an server enviroment had language file in theyr mods, the could not merge it with client language, then the mods are messing with the language keys, it is normaly, a lot of mods using own language files, that they had no issues with it, but a lot of mods also have problems with the same issues.

it is on modders side to fix this, this is a problem, but i don't know how you could fix this, 

the issue is on server side only

**Comment by NiceKaleido** [comment]
Since the mod is just an auto converted version of a data pack there is no real way to fix this for me. 

But u could just use the data pack version instead. It wont load the language file if u dont pack it in your resource pack folder

**Comment by suerion** [comment]
Fabric API does fix it ;)
